/* ============================================================
   図形推論 (Matrix) — test config + procedural item generator.
   Registers with the shared engine in assets/lab.js. Load after
   lab.js + lab-share.js and before this page's own inline <script>.

   Self-authored 3x3 pattern-completion items — not a reproduction or
   imitation of any published matrix-reasoning test. Items are
   generated by a small seeded PRNG (seed = today's local date
   string), so a retake on the same day shows the same 12 items and
   a retake on a later day shows a different set. Deterministic
   generation lives entirely in generateItems(), called by the
   page's inline script; the returned {items, rand} lets the page
   continue the same PRNG stream for shuffling answer options.

   Cell descriptor: {shape: 'circle'|'square'|'triangle',
   count: 1-4, rotation: 0|90|180|270, fill: 'filled'|'outline',
   size: 0.72-1.3}. Rotation is only used as a distinguishing axis
   when shape is 'triangle' — a plain circle/square looks identical
   before and after a 90°-multiple rotation, so using rotation as a
   distractor axis on those shapes would silently produce two
   pixel-identical options. Every family/distractor below respects
   this.

   Item plan (rising difficulty):
   1-4   one rule each (shape progression, count progression, fill
         alternation, size progression), "far" distractors.
   5-8   one rule each, including rotation for the first time,
         "closer" (more confusable) distractors.
   9-12  two rules combined on the same grid.

   Thresholds: grade D — self-authored, unstandardized, no published
   norms. tierValue passed to Lab.tier.forValue is INVERTED
   (12 − correctCount) because the headline (correct count) is
   higher-is-better while the shared tier engine assumes lower
   tierValue = better, matching the PVT/Stroop convention.
   ============================================================ */
(function () {
  if (!window.Lab) return;

  var SHAPES = ['circle', 'square', 'triangle'];

  function oppFill(f) { return f === 'filled' ? 'outline' : 'filled'; }

  function pickOther(arr, val, rand) {
    var rest = arr.filter(function (v) { return v !== val; });
    return rest[Math.floor(rand() * rest.length)];
  }

  function pickShape(rand) { return SHAPES[Math.floor(rand() * SHAPES.length)]; }

  // ---------------------------------------------------------
  // Seeded PRNG — xfnv1a hash seeds a mulberry32 generator, so the
  // same date string always produces the same rand() sequence.
  // ---------------------------------------------------------
  function xfnv1a(str) {
    var h = 1779033703 ^ str.length;
    for (var i = 0; i < str.length; i++) {
      h = Math.imul(h ^ str.charCodeAt(i), 3432918353);
      h = (h << 13) | (h >>> 19);
    }
    return function () {
      h = Math.imul(h ^ (h >>> 16), 2246822507);
      h = Math.imul(h ^ (h >>> 13), 3266489909);
      h ^= h >>> 16;
      return h >>> 0;
    };
  }
  function mulberry32(seed) {
    return function () {
      seed |= 0;
      seed = (seed + 0x6D2B79F5) | 0;
      var t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
      t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  }
  function makeRand(seedStr) { return mulberry32(xfnv1a(seedStr)()); }

  function shuffleWithRand(arr, rand) {
    var a = arr.slice();
    for (var i = a.length - 1; i > 0; i--) {
      var j = Math.floor(rand() * (i + 1));
      var t = a[i]; a[i] = a[j]; a[j] = t;
    }
    return a;
  }

  // ---------------------------------------------------------
  // Items 1-4 — one easy rule, far (easily distinguishable) options.
  // ---------------------------------------------------------
  function item1(rand) { // shape progression across columns
    var fill = rand() < 0.5 ? 'filled' : 'outline';
    var grid = [];
    for (var r = 0; r < 3; r++) for (var c = 0; c < 3; c++) grid.push({ shape: SHAPES[c], count: 1, rotation: 0, fill: fill, size: 1 });
    var correct = grid[8];
    var distractors = [
      { shape: 'circle', count: 1, rotation: 0, fill: fill, size: 1 },
      { shape: 'square', count: 1, rotation: 0, fill: fill, size: 1 },
      { shape: 'triangle', count: 1, rotation: 0, fill: oppFill(fill), size: 1 },
      { shape: 'triangle', count: 2, rotation: 0, fill: fill, size: 1 },
      { shape: 'triangle', count: 1, rotation: 0, fill: fill, size: 1.3 }
    ];
    return { grid: grid, correct: correct, distractors: distractors };
  }

  function item2(rand) { // count progression across rows (1,2,3 dots)
    var shape = pickShape(rand);
    var fill = rand() < 0.5 ? 'filled' : 'outline';
    var other = pickOther(SHAPES, shape, rand);
    var grid = [];
    for (var r = 0; r < 3; r++) for (var c = 0; c < 3; c++) grid.push({ shape: shape, count: r + 1, rotation: 0, fill: fill, size: 1 });
    var correct = grid[8];
    var distractors = [
      { shape: shape, count: 1, rotation: 0, fill: fill, size: 1 },
      { shape: shape, count: 2, rotation: 0, fill: fill, size: 1 },
      { shape: shape, count: 4, rotation: 0, fill: fill, size: 1 },
      { shape: other, count: 3, rotation: 0, fill: fill, size: 1 },
      { shape: shape, count: 3, rotation: 0, fill: oppFill(fill), size: 1 }
    ];
    return { grid: grid, correct: correct, distractors: distractors };
  }

  function item3(rand) { // fill/outline alternation, checkerboard by (row+col)
    var shape = pickShape(rand);
    var other = pickOther(SHAPES, shape, rand);
    var grid = [];
    for (var r = 0; r < 3; r++) for (var c = 0; c < 3; c++) {
      var fill = (r + c) % 2 === 0 ? 'filled' : 'outline';
      grid.push({ shape: shape, count: 1, rotation: 0, fill: fill, size: 1 });
    }
    var correct = grid[8];
    var opp = oppFill(correct.fill);
    var lastAxis = shape === 'triangle'
      ? { shape: shape, count: 1, rotation: 90, fill: correct.fill, size: 1 }
      : { shape: shape, count: 1, rotation: 0, fill: correct.fill, size: 0.72 };
    var distractors = [
      { shape: shape, count: 1, rotation: 0, fill: opp, size: 1 },
      { shape: other, count: 1, rotation: 0, fill: correct.fill, size: 1 },
      { shape: shape, count: 2, rotation: 0, fill: correct.fill, size: 1 },
      { shape: shape, count: 1, rotation: 0, fill: correct.fill, size: 1.3 },
      lastAxis
    ];
    return { grid: grid, correct: correct, distractors: distractors };
  }

  function item4(rand) { // size progression across columns
    var shape = pickShape(rand);
    var other = pickOther(SHAPES, shape, rand);
    var fill = rand() < 0.5 ? 'filled' : 'outline';
    var sizes = [0.72, 1, 1.3];
    var grid = [];
    for (var r = 0; r < 3; r++) for (var c = 0; c < 3; c++) grid.push({ shape: shape, count: 1, rotation: 0, fill: fill, size: sizes[c] });
    var correct = grid[8];
    var distractors = [
      { shape: shape, count: 1, rotation: 0, fill: fill, size: 0.72 },
      { shape: shape, count: 1, rotation: 0, fill: fill, size: 1 },
      { shape: shape, count: 1, rotation: 0, fill: oppFill(fill), size: 1.3 },
      { shape: other, count: 1, rotation: 0, fill: fill, size: 1.3 },
      { shape: shape, count: 2, rotation: 0, fill: fill, size: 1.3 }
    ];
    return { grid: grid, correct: correct, distractors: distractors };
  }

  // ---------------------------------------------------------
  // Items 5-8 — one rule, rotation introduced, closer distractors.
  // ---------------------------------------------------------
  function item5(rand) { // rotation across columns (triangle — the only shape where 90°-step rotation reads visibly)
    var fill = rand() < 0.5 ? 'filled' : 'outline';
    var rots = [0, 90, 180];
    var grid = [];
    for (var r = 0; r < 3; r++) for (var c = 0; c < 3; c++) grid.push({ shape: 'triangle', count: 1, rotation: rots[c], fill: fill, size: 1 });
    var correct = grid[8];
    var distractors = [
      { shape: 'triangle', count: 1, rotation: 0, fill: fill, size: 1 },
      { shape: 'triangle', count: 1, rotation: 90, fill: fill, size: 1 },
      { shape: 'triangle', count: 1, rotation: 270, fill: fill, size: 1 },
      { shape: 'triangle', count: 1, rotation: 180, fill: oppFill(fill), size: 1 },
      { shape: 'square', count: 1, rotation: 180, fill: fill, size: 1 }
    ];
    return { grid: grid, correct: correct, distractors: distractors };
  }

  function item6(rand) { // shape progression, non-canonical order + closer distractors (no rotation axis — order already varies)
    var seqs = [['circle', 'square', 'triangle'], ['square', 'triangle', 'circle'], ['triangle', 'circle', 'square']];
    var shapes = seqs[Math.floor(rand() * seqs.length)];
    var fill = rand() < 0.5 ? 'filled' : 'outline';
    var grid = [];
    for (var r = 0; r < 3; r++) for (var c = 0; c < 3; c++) grid.push({ shape: shapes[c], count: 1, rotation: 0, fill: fill, size: 1 });
    var correct = grid[8];
    var distractors = [
      { shape: shapes[1], count: 1, rotation: 0, fill: fill, size: 1 },
      { shape: shapes[0], count: 1, rotation: 0, fill: fill, size: 1 },
      { shape: correct.shape, count: 1, rotation: 0, fill: oppFill(fill), size: 1 },
      { shape: correct.shape, count: 1, rotation: 0, fill: fill, size: 1.15 },
      { shape: correct.shape, count: 2, rotation: 0, fill: fill, size: 1 }
    ];
    return { grid: grid, correct: correct, distractors: distractors };
  }

  function item7(rand) { // count progression, closer distractors (off-by-one count emphasized)
    var shape = pickShape(rand);
    var other = pickOther(SHAPES, shape, rand);
    var fill = rand() < 0.5 ? 'filled' : 'outline';
    var grid = [];
    for (var r = 0; r < 3; r++) for (var c = 0; c < 3; c++) grid.push({ shape: shape, count: r + 1, rotation: 0, fill: fill, size: 1 });
    var correct = grid[8];
    var distractors = [
      { shape: shape, count: 2, rotation: 0, fill: fill, size: 1 },
      { shape: other, count: 3, rotation: 0, fill: fill, size: 1 },
      { shape: shape, count: 3, rotation: 0, fill: oppFill(fill), size: 1 },
      { shape: shape, count: 3, rotation: 0, fill: fill, size: 1.15 },
      { shape: shape, count: 1, rotation: 0, fill: fill, size: 1 }
    ];
    return { grid: grid, correct: correct, distractors: distractors };
  }

  function item8(rand) { // size progression, closer steps
    var shape = pickShape(rand);
    var other = pickOther(SHAPES, shape, rand);
    var fill = rand() < 0.5 ? 'filled' : 'outline';
    var sizes = [0.85, 1, 1.15];
    var grid = [];
    for (var r = 0; r < 3; r++) for (var c = 0; c < 3; c++) grid.push({ shape: shape, count: 1, rotation: 0, fill: fill, size: sizes[c] });
    var correct = grid[8];
    var lastAxis = shape === 'triangle'
      ? { shape: shape, count: 1, rotation: 90, fill: fill, size: 1.15 }
      : { shape: shape, count: 2, rotation: 0, fill: fill, size: 1.15 };
    var distractors = [
      { shape: shape, count: 1, rotation: 0, fill: fill, size: 0.85 },
      { shape: shape, count: 1, rotation: 0, fill: fill, size: 1 },
      { shape: shape, count: 1, rotation: 0, fill: oppFill(fill), size: 1.15 },
      { shape: other, count: 1, rotation: 0, fill: fill, size: 1.15 },
      lastAxis
    ];
    return { grid: grid, correct: correct, distractors: distractors };
  }

  // ---------------------------------------------------------
  // Items 9-12 — two rules combined on the same grid.
  // ---------------------------------------------------------
  function item9(rand) { // shape (columns) x count (rows)
    var fill = rand() < 0.5 ? 'filled' : 'outline';
    var grid = [];
    for (var r = 0; r < 3; r++) for (var c = 0; c < 3; c++) grid.push({ shape: SHAPES[c], count: r + 1, rotation: 0, fill: fill, size: 1 });
    var correct = grid[8];
    var distractors = [
      { shape: 'circle', count: 3, rotation: 0, fill: fill, size: 1 },
      { shape: 'square', count: 3, rotation: 0, fill: fill, size: 1 },
      { shape: 'triangle', count: 2, rotation: 0, fill: fill, size: 1 },
      { shape: 'triangle', count: 1, rotation: 0, fill: fill, size: 1 },
      { shape: 'triangle', count: 3, rotation: 0, fill: oppFill(fill), size: 1 }
    ];
    return { grid: grid, correct: correct, distractors: distractors };
  }

  function item10(rand) { // rotation (columns, triangle) x fill checkerboard
    var rots = [0, 90, 180];
    var grid = [];
    for (var r = 0; r < 3; r++) for (var c = 0; c < 3; c++) {
      var fill = (r + c) % 2 === 0 ? 'filled' : 'outline';
      grid.push({ shape: 'triangle', count: 1, rotation: rots[c], fill: fill, size: 1 });
    }
    var correct = grid[8];
    var distractors = [
      { shape: 'triangle', count: 1, rotation: 180, fill: oppFill(correct.fill), size: 1 },
      { shape: 'triangle', count: 1, rotation: 90, fill: correct.fill, size: 1 },
      { shape: 'triangle', count: 1, rotation: 0, fill: correct.fill, size: 1 },
      { shape: 'triangle', count: 1, rotation: 270, fill: correct.fill, size: 1 },
      { shape: 'square', count: 1, rotation: 180, fill: correct.fill, size: 1 }
    ];
    return { grid: grid, correct: correct, distractors: distractors };
  }

  function item11(rand) { // size (columns) x shape (rows)
    var perms = [['circle', 'square', 'triangle'], ['square', 'triangle', 'circle'], ['triangle', 'circle', 'square']];
    var shapesR = perms[Math.floor(rand() * perms.length)];
    var sizes = [0.72, 1, 1.3];
    var fill = rand() < 0.5 ? 'filled' : 'outline';
    var grid = [];
    for (var r = 0; r < 3; r++) for (var c = 0; c < 3; c++) grid.push({ shape: shapesR[r], count: 1, rotation: 0, fill: fill, size: sizes[c] });
    var correct = grid[8];
    var distractors = [
      { shape: shapesR[2], count: 1, rotation: 0, fill: fill, size: 1 },
      { shape: shapesR[2], count: 1, rotation: 0, fill: fill, size: 0.72 },
      { shape: shapesR[0], count: 1, rotation: 0, fill: fill, size: 1.3 },
      { shape: shapesR[1], count: 1, rotation: 0, fill: fill, size: 1.3 },
      { shape: shapesR[2], count: 1, rotation: 0, fill: oppFill(fill), size: 1.3 }
    ];
    return { grid: grid, correct: correct, distractors: distractors };
  }

  function item12(rand) { // count (rows) x rotation (columns, triangle only)
    var rots = [0, 90, 180];
    var grid = [];
    for (var r = 0; r < 3; r++) for (var c = 0; c < 3; c++) grid.push({ shape: 'triangle', count: r + 1, rotation: rots[c], fill: 'filled', size: 1 });
    var correct = grid[8];
    var distractors = [
      { shape: 'triangle', count: 2, rotation: 180, fill: 'filled', size: 1 },
      { shape: 'triangle', count: 3, rotation: 90, fill: 'filled', size: 1 },
      { shape: 'triangle', count: 3, rotation: 0, fill: 'filled', size: 1 },
      { shape: 'triangle', count: 1, rotation: 180, fill: 'filled', size: 1 },
      { shape: 'triangle', count: 3, rotation: 180, fill: 'outline', size: 1 }
    ];
    return { grid: grid, correct: correct, distractors: distractors };
  }

  function generateItems(seedStr) {
    var rand = makeRand(seedStr);
    var builders = [item1, item2, item3, item4, item5, item6, item7, item8, item9, item10, item11, item12];
    var items = builders.map(function (fn) { return fn(rand); });
    return { items: items, rand: rand };
  }

  Lab.registerTest({
    id: 'matrix',
    name: '図形推論',
    path: 'matrix',
    unit: '/ 12問',
    headlineLabel: '正解数',
    thresholds: [0, 1, 2, 3, 5, 7, Infinity],
    labels: [
      '正解 12問', '正解 11問', '正解 10問', '正解 9問',
      '正解 7〜8問', '正解 5〜6問', '正解 4問以下'
    ],
    referenceGrade: 'D',
    referenceNote: 'このテストは自作の課題で、標準化された基準値はありません（根拠D）。繰り返すほど規則の見つけ方に慣れて速く・正確になりやすい点にも注意してください。他の人や集団の平均との比較はできません。',
    sources: [],
    shareLead: '図形推論',
    // Test-specific extras, read back as Lab.tests.matrix.<field>.
    totalItems: 12,
    timeLimitMs: 60000,
    generateItems: generateItems,
    shuffleWithRand: shuffleWithRand
  });
})();
